project:
  type: website

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: web_pages/photos.qmd
        text: Pictures
      - href: web_pages/drawings.qmd
        text: Drawings
      - href: web_pages/about.qmd
        text: About
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



